import { formatScore } from '@/lib/utils'
import { outcomeLabel, verdictLabel } from '@/lib/report-labels'
import type { InterviewReport } from '@/types/api'

interface ReportPrintViewProps {
  report: InterviewReport
}

function PrintList({ title, items }: { title: string; items: string[] }) {
  return (
    <section className="report-print-section">
      <h2>{title}</h2>
      {items.length ? (
        <ol className="report-print-list">
          {items.map((item, index) => (
            <li key={`${index}-${item.slice(0, 20)}`}>{item}</li>
          ))}
        </ol>
      ) : (
        <p className="report-print-muted">None noted.</p>
      )}
    </section>
  )
}

export function ReportPrintView({ report }: ReportPrintViewProps) {
  const completedLabel = report.completed_at
    ? new Date(report.completed_at).toLocaleString()
    : new Date().toLocaleString()

  const stopped = outcomeLabel(report.stopped_reason)

  return (
    <article className="report-print-document">
      <header className="report-print-header">
        <p className="report-print-brand">SpeechAgent — Interview Report</p>
        <h1>{report.candidate_name}</h1>
        <p className="report-print-subtitle">
          Completed {completedLabel} · Session {report.bot_id}
        </p>
      </header>

      <section className="report-print-outcome">
        <strong>Interview outcome:</strong> {stopped}
      </section>

      <section className="report-print-section">
        <h2>Performance summary</h2>
        <dl className="report-print-summary">
          <div>
            <dt>Overall score</dt>
            <dd>{formatScore(report.overall_average)} / 10</dd>
          </div>
          <div>
            <dt>Recent average (last {report.rolling_window} answers)</dt>
            <dd>{formatScore(report.last_4_average)} / 10</dd>
          </div>
          <div>
            <dt>Questions answered</dt>
            <dd>
              {report.questions_scored} of {report.questions_planned}
            </dd>
          </div>
          <div>
            <dt>Pass threshold</dt>
            <dd>{report.continue_threshold.toFixed(1)} / 10</dd>
          </div>
        </dl>
        <p className="report-print-note">
          Scores are based on answer quality, relevance, and confidence during the interview.
        </p>
      </section>

      <PrintList title="Areas to develop" items={report.summary_develop} />
      <PrintList title="Suggested improvements" items={report.summary_fix} />

      <section className="report-print-section">
        <h2>Question-by-question feedback</h2>
        <p className="report-print-note">
          Each section shows the question asked, your answer, your score, and feedback to help
          you improve.
        </p>

        {report.per_question.map((record) => (
          <section key={record.question_index} className="report-print-question">
            <div className="report-print-question-head">
              <h3>
                Question {record.question_index}
                <span className="report-print-meta">
                  {' '}
                  · {record.difficulty} · {record.source}
                </span>
              </h3>
              <p>
                Score: <strong>{record.score}/10</strong> ({verdictLabel(record.score)})
              </p>
            </div>

            <p className="report-print-label">Question</p>
            <p className="report-print-body">{record.question_text}</p>

            <p className="report-print-label">Your answer</p>
            <p className="report-print-body report-print-answer">
              {record.answer_text || 'No answer recorded.'}
            </p>

            <table className="report-print-table">
              <thead>
                <tr>
                  <th>Confident</th>
                  <th>Relevant</th>
                  <th>Strengths noted</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>{record.confident ? 'Yes' : 'No'}</td>
                  <td>{record.relevant ? 'Yes' : 'No'}</td>
                  <td>{record.strengths || '—'}</td>
                </tr>
              </tbody>
            </table>

            <div className="report-print-feedback">
              <div>
                <p className="report-print-label">What to develop</p>
                <p>{record.develop || '—'}</p>
              </div>
              <div>
                <p className="report-print-label">How to improve</p>
                <p>{record.fix || '—'}</p>
              </div>
            </div>
          </section>
        ))}
      </section>

      <footer className="report-print-footer">
        This report was generated by SpeechAgent. Use the feedback above to prepare for your next
        interview.
      </footer>
    </article>
  )
}
