export const queryKeys = {
  health: ['health'] as const,
  sessions: ['sessions'] as const,
  reports: ['reports'] as const,
  users: ['users'] as const,
  candidates: ['candidates'] as const,
  candidatesByJob: (jobId: string | null) => ['candidates', 'job', jobId ?? 'none'] as const,
  jobPostings: ['jobPostings'] as const,
  jobPosting: (jobId: string) => ['jobPosting', jobId] as const,
  jobResumes: (jobId: string) => ['jobResumes', jobId] as const,
  scheduledInterviews: ['scheduledInterviews'] as const,
  atsSettings: ['atsSettings'] as const,
  atsCandidates: ['atsCandidates'] as const,
  atsJobs: ['atsJobs'] as const,
  uploadBatch: (batchId: string) => ['uploadBatch', batchId] as const,
  codingTasks: ['codingTasks'] as const,
  codingBank: ['codingBank'] as const,
  codingBankStatus: ['codingBankStatus'] as const,
  codingAssignPreview: (language: string, count: number) =>
    ['codingAssignPreview', language, count] as const,
  codingDomains: ['codingDomains'] as const,
  codingDomainTasks: (domainId: string, ownedOnly = true) =>
    ['codingDomainTasks', domainId, ownedOnly ? 'owned' : 'all'] as const,
  codingSessionByBot: (botId: string) => ['codingSession', 'bot', botId] as const,
  codingSessionByInterview: (interviewId: string) =>
    ['codingSession', 'interview', interviewId] as const,
  codingDemo: (token: string) => ['codingDemo', token] as const,
  codingPublic: (token: string) => ['codingPublic', token] as const,
  status: (botId: string) => ['status', botId] as const,
  report: (botId: string) => ['report', botId] as const,
  feedback: (botId: string) => ['feedback', botId] as const,
  feedbackContext: (botId: string) => ['feedbackContext', botId] as const,
}
