export const queryKeys = {
  health: ['health'] as const,
  sessions: ['sessions'] as const,
  reports: ['reports'] as const,
  users: ['users'] as const,
  candidates: ['candidates'] as const,
  jobPostings: ['jobPostings'] as const,
  scheduledInterviews: ['scheduledInterviews'] as const,
  atsSettings: ['atsSettings'] as const,
  atsCandidates: ['atsCandidates'] as const,
  atsJobs: ['atsJobs'] as const,
  status: (botId: string) => ['status', botId] as const,
  report: (botId: string) => ['report', botId] as const,
  feedback: (botId: string) => ['feedback', botId] as const,
  feedbackContext: (botId: string) => ['feedbackContext', botId] as const,
}
